"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
from .. import common
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SchematicJobPageSize:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicJobPageSizeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicJobPageSize.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SJPS_UNKNOWN: _SchematicJobPageSize.ValueType
    SJPS_AUTO: _SchematicJobPageSize.ValueType
    'Auto-select page size from sheet settings'
    SJPS_A4: _SchematicJobPageSize.ValueType
    'Force A4 page size'
    SJPS_A: _SchematicJobPageSize.ValueType
    'Force ANSI A page size'

class SchematicJobPageSize(_SchematicJobPageSize, metaclass=_SchematicJobPageSizeEnumTypeWrapper):
    """Page size override used for schematic plotting jobs"""
SJPS_UNKNOWN: SchematicJobPageSize.ValueType
SJPS_AUTO: SchematicJobPageSize.ValueType
'Auto-select page size from sheet settings'
SJPS_A4: SchematicJobPageSize.ValueType
'Force A4 page size'
SJPS_A: SchematicJobPageSize.ValueType
'Force ANSI A page size'
global___SchematicJobPageSize = SchematicJobPageSize

class _SchematicNetlistFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicNetlistFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicNetlistFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SNF_UNKNOWN: _SchematicNetlistFormat.ValueType
    SNF_KICAD_XML: _SchematicNetlistFormat.ValueType
    SNF_KICAD_SEXPR: _SchematicNetlistFormat.ValueType
    SNF_ORCAD_PCB2: _SchematicNetlistFormat.ValueType
    SNF_CADSTAR: _SchematicNetlistFormat.ValueType
    SNF_SPICE: _SchematicNetlistFormat.ValueType
    SNF_SPICE_MODEL: _SchematicNetlistFormat.ValueType
    SNF_PADS: _SchematicNetlistFormat.ValueType
    SNF_ALLEGRO: _SchematicNetlistFormat.ValueType

class SchematicNetlistFormat(_SchematicNetlistFormat, metaclass=_SchematicNetlistFormatEnumTypeWrapper):
    """Netlist format for schematic netlist export."""
SNF_UNKNOWN: SchematicNetlistFormat.ValueType
SNF_KICAD_XML: SchematicNetlistFormat.ValueType
SNF_KICAD_SEXPR: SchematicNetlistFormat.ValueType
SNF_ORCAD_PCB2: SchematicNetlistFormat.ValueType
SNF_CADSTAR: SchematicNetlistFormat.ValueType
SNF_SPICE: SchematicNetlistFormat.ValueType
SNF_SPICE_MODEL: SchematicNetlistFormat.ValueType
SNF_PADS: SchematicNetlistFormat.ValueType
SNF_ALLEGRO: SchematicNetlistFormat.ValueType
global___SchematicNetlistFormat = SchematicNetlistFormat

class _BOMSortDirection:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BOMSortDirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BOMSortDirection.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BSD_UNKNOWN: _BOMSortDirection.ValueType
    BSD_ASCENDING: _BOMSortDirection.ValueType
    BSD_DESCENDING: _BOMSortDirection.ValueType

class BOMSortDirection(_BOMSortDirection, metaclass=_BOMSortDirectionEnumTypeWrapper):
    ...
BSD_UNKNOWN: BOMSortDirection.ValueType
BSD_ASCENDING: BOMSortDirection.ValueType
BSD_DESCENDING: BOMSortDirection.ValueType
global___BOMSortDirection = BOMSortDirection

@typing.final
class SchematicPlotSettings(google.protobuf.message.Message):
    """Shared plot options for schematic plot exports"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DRAWING_SHEET_FIELD_NUMBER: builtins.int
    DEFAULT_FONT_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    PLOT_ALL_FIELD_NUMBER: builtins.int
    PLOT_DRAWING_SHEET_FIELD_NUMBER: builtins.int
    PLOT_PAGES_FIELD_NUMBER: builtins.int
    SHOW_HOP_OVER_FIELD_NUMBER: builtins.int
    BLACK_AND_WHITE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    USE_BACKGROUND_COLOR_FIELD_NUMBER: builtins.int
    MIN_PEN_WIDTH_FIELD_NUMBER: builtins.int
    THEME_FIELD_NUMBER: builtins.int
    drawing_sheet: builtins.str
    default_font: builtins.str
    variant: builtins.str
    plot_all: builtins.bool
    plot_drawing_sheet: builtins.bool
    show_hop_over: builtins.bool
    black_and_white: builtins.bool
    page_size: global___SchematicJobPageSize.ValueType
    use_background_color: builtins.bool
    min_pen_width: builtins.int
    theme: builtins.str

    @property
    def plot_pages(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        ...

    def __init__(self, *, drawing_sheet: builtins.str=..., default_font: builtins.str=..., variant: builtins.str=..., plot_all: builtins.bool=..., plot_drawing_sheet: builtins.bool=..., plot_pages: collections.abc.Iterable[builtins.str] | None=..., show_hop_over: builtins.bool=..., black_and_white: builtins.bool=..., page_size: global___SchematicJobPageSize.ValueType=..., use_background_color: builtins.bool=..., min_pen_width: builtins.int=..., theme: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['black_and_white', b'black_and_white', 'default_font', b'default_font', 'drawing_sheet', b'drawing_sheet', 'min_pen_width', b'min_pen_width', 'page_size', b'page_size', 'plot_all', b'plot_all', 'plot_drawing_sheet', b'plot_drawing_sheet', 'plot_pages', b'plot_pages', 'show_hop_over', b'show_hop_over', 'theme', b'theme', 'use_background_color', b'use_background_color', 'variant', b'variant']) -> None:
        ...
global___SchematicPlotSettings = SchematicPlotSettings

@typing.final
class RunSchematicJobExportSvg(google.protobuf.message.Message):
    """Plots a schematic to SVG. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___SchematicPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___SchematicPlotSettings | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> None:
        ...
global___RunSchematicJobExportSvg = RunSchematicJobExportSvg

@typing.final
class RunSchematicJobExportDxf(google.protobuf.message.Message):
    """Plots a schematic to DXF. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___SchematicPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___SchematicPlotSettings | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> None:
        ...
global___RunSchematicJobExportDxf = RunSchematicJobExportDxf

@typing.final
class RunSchematicJobExportPdf(google.protobuf.message.Message):
    """Plots a schematic to PDF. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int
    PROPERTY_POPUPS_FIELD_NUMBER: builtins.int
    HIERARCHICAL_LINKS_FIELD_NUMBER: builtins.int
    INCLUDE_METADATA_FIELD_NUMBER: builtins.int
    property_popups: builtins.bool
    hierarchical_links: builtins.bool
    include_metadata: builtins.bool

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___SchematicPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___SchematicPlotSettings | None=..., property_popups: builtins.bool=..., hierarchical_links: builtins.bool=..., include_metadata: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['hierarchical_links', b'hierarchical_links', 'include_metadata', b'include_metadata', 'job_settings', b'job_settings', 'plot_settings', b'plot_settings', 'property_popups', b'property_popups']) -> None:
        ...
global___RunSchematicJobExportPdf = RunSchematicJobExportPdf

@typing.final
class RunSchematicJobExportPs(google.protobuf.message.Message):
    """Plots a schematic to PostScript. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___SchematicPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___SchematicPlotSettings | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> None:
        ...
global___RunSchematicJobExportPs = RunSchematicJobExportPs

@typing.final
class RunSchematicJobExportNetlist(google.protobuf.message.Message):
    """Exports a schematic netlist. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    VARIANT_NAME_FIELD_NUMBER: builtins.int
    format: global___SchematicNetlistFormat.ValueType
    variant_name: builtins.str
    'If the design contains variants, this field can be set to the name of a variant to use\n    for the BOM export\n    '

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., format: global___SchematicNetlistFormat.ValueType=..., variant_name: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['format', b'format', 'job_settings', b'job_settings', 'variant_name', b'variant_name']) -> None:
        ...
global___RunSchematicJobExportNetlist = RunSchematicJobExportNetlist

@typing.final
class BOMFormatSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRESET_NAME_FIELD_NUMBER: builtins.int
    FIELD_DELIMITER_FIELD_NUMBER: builtins.int
    STRING_DELIMITER_FIELD_NUMBER: builtins.int
    REF_DELIMITER_FIELD_NUMBER: builtins.int
    REF_RANGE_DELIMITER_FIELD_NUMBER: builtins.int
    KEEP_TABS_FIELD_NUMBER: builtins.int
    KEEP_LINE_BREAKS_FIELD_NUMBER: builtins.int
    preset_name: builtins.str
    "If supplied, will apply a preset to the other format settings.  Built-in values 'CSV', 'TSV',\n    and 'Semicolons' are always available, as well as any user-saved presets.\n    "
    field_delimiter: builtins.str
    'Delimiter between fields (columns) in a data row'
    string_delimiter: builtins.str
    'Character to use for quoting strings'
    ref_delimiter: builtins.str
    'Delimiter between reference designators when exporting a list (e.g. "R1,R3,R5")'
    ref_range_delimiter: builtins.str
    'Delimiter between reference designators when exporting a range (e.g. "R1-R10")'
    keep_tabs: builtins.bool
    'Whether tab characters in field values will be preserved when exporting or stripped (default)'
    keep_line_breaks: builtins.bool
    'Whether line breaks in field values will be preserved when exporting or stripped (default)'

    def __init__(self, *, preset_name: builtins.str=..., field_delimiter: builtins.str=..., string_delimiter: builtins.str=..., ref_delimiter: builtins.str=..., ref_range_delimiter: builtins.str=..., keep_tabs: builtins.bool=..., keep_line_breaks: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['field_delimiter', b'field_delimiter', 'keep_line_breaks', b'keep_line_breaks', 'keep_tabs', b'keep_tabs', 'preset_name', b'preset_name', 'ref_delimiter', b'ref_delimiter', 'ref_range_delimiter', b'ref_range_delimiter', 'string_delimiter', b'string_delimiter']) -> None:
        ...
global___BOMFormatSettings = BOMFormatSettings

@typing.final
class BOMField(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    GROUP_BY_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the field in KiCad to export'
    label: builtins.str
    'The name to give the field in the exported BOM (i.e. the column header name)'
    group_by: builtins.bool
    'Whether or not to group exported components by this field'

    def __init__(self, *, name: builtins.str=..., label: builtins.str=..., group_by: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['group_by', b'group_by', 'label', b'label', 'name', b'name']) -> None:
        ...
global___BOMField = BOMField

@typing.final
class BOMFieldSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRESET_NAME_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    SORT_FIELD_FIELD_NUMBER: builtins.int
    SORT_DIRECTION_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    preset_name: builtins.str
    "If supplied, will apply a default or user-stored preset to the other field settings.\n    Default values available include 'Default Editing', 'Grouped By Value',\n    'Grouped By Value and Footprint', and 'Attributes'.\n    "
    sort_field: builtins.str
    sort_direction: global___BOMSortDirection.ValueType
    'Sort direction; defaults to ascending if unspecified'
    filter: builtins.str

    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BOMField]:
        """An ordered list of fields to export"""

    def __init__(self, *, preset_name: builtins.str=..., fields: collections.abc.Iterable[global___BOMField] | None=..., sort_field: builtins.str=..., sort_direction: global___BOMSortDirection.ValueType=..., filter: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['fields', b'fields', 'filter', b'filter', 'preset_name', b'preset_name', 'sort_direction', b'sort_direction', 'sort_field', b'sort_field']) -> None:
        ...
global___BOMFieldSettings = BOMFieldSettings

@typing.final
class RunSchematicJobExportBOM(google.protobuf.message.Message):
    """Exports a schematic bill of materials. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    EXCLUDE_DNP_FIELD_NUMBER: builtins.int
    GROUP_SYMBOLS_FIELD_NUMBER: builtins.int
    VARIANT_NAME_FIELD_NUMBER: builtins.int
    exclude_dnp: builtins.bool
    'If true, "do not populate" components will be omitted from the exported BOM'
    group_symbols: builtins.bool
    'If true, will group symbols into a single BOM row when they have matching values for any\n    fields where group_by is true\n    '
    variant_name: builtins.str
    'If the design contains variants, this field can be set to the name of a variant to use\n    for the BOM export\n    '

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def format(self) -> global___BOMFormatSettings:
        ...

    @property
    def fields(self) -> global___BOMFieldSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., format: global___BOMFormatSettings | None=..., fields: global___BOMFieldSettings | None=..., exclude_dnp: builtins.bool=..., group_symbols: builtins.bool=..., variant_name: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['fields', b'fields', 'format', b'format', 'job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['exclude_dnp', b'exclude_dnp', 'fields', b'fields', 'format', b'format', 'group_symbols', b'group_symbols', 'job_settings', b'job_settings', 'variant_name', b'variant_name']) -> None:
        ...
global___RunSchematicJobExportBOM = RunSchematicJobExportBOM