"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
from .. import common
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SchematicLayer:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicLayerEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicLayer.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SL_UNKNOWN: _SchematicLayer.ValueType

class SchematicLayer(_SchematicLayer, metaclass=_SchematicLayerEnumTypeWrapper):
    ...
SL_UNKNOWN: SchematicLayer.ValueType
global___SchematicLayer = SchematicLayer

@typing.final
class Line(google.protobuf.message.Message):
    """/ Represents a schematic line segment, which may be a wire, bus, or graphical line"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    LAYER_FIELD_NUMBER: builtins.int
    layer: global___SchematicLayer.ValueType
    '*\n    One of: LAYER_BUS, LAYER_WIRE, LAYER_NOTES\n    '

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def start(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def end(self) -> common.types.base_types_pb2.Vector2:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., start: common.types.base_types_pb2.Vector2 | None=..., end: common.types.base_types_pb2.Vector2 | None=..., layer: global___SchematicLayer.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['end', b'end', 'id', b'id', 'start', b'start']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['end', b'end', 'id', b'id', 'layer', b'layer', 'start', b'start']) -> None:
        ...
global___Line = Line

@typing.final
class Text(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TEXT_FIELD_NUMBER: builtins.int

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    def __init__(self, *, text: common.types.base_types_pb2.Text | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['text', b'text']) -> None:
        ...
global___Text = Text

@typing.final
class LocalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> global___Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: global___Text | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> None:
        ...
global___LocalLabel = LocalLabel

@typing.final
class GlobalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> global___Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: global___Text | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> None:
        ...
global___GlobalLabel = GlobalLabel

@typing.final
class HierarchicalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> global___Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: global___Text | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> None:
        ...
global___HierarchicalLabel = HierarchicalLabel

@typing.final
class DirectiveLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> global___Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: global___Text | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> None:
        ...
global___DirectiveLabel = DirectiveLabel