"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from .. import board
import builtins
import collections.abc
from .. import common
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PlotDrillMarks:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PlotDrillMarksEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PlotDrillMarks.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PDM_UNKNOWN: _PlotDrillMarks.ValueType
    PDM_NONE: _PlotDrillMarks.ValueType
    'Do not draw drill holes.'
    PDM_SMALL: _PlotDrillMarks.ValueType
    'Draw small fixed-size drill holes.'
    PDM_FULL: _PlotDrillMarks.ValueType
    'Draw drill holes using their real size.'

class PlotDrillMarks(_PlotDrillMarks, metaclass=_PlotDrillMarksEnumTypeWrapper):
    """Controls whether drill holes are drawn in plot outputs that support hole marks."""
PDM_UNKNOWN: PlotDrillMarks.ValueType
PDM_NONE: PlotDrillMarks.ValueType
'Do not draw drill holes.'
PDM_SMALL: PlotDrillMarks.ValueType
'Draw small fixed-size drill holes.'
PDM_FULL: PlotDrillMarks.ValueType
'Draw drill holes using their real size.'
global___PlotDrillMarks = PlotDrillMarks

class _Board3DFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _Board3DFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Board3DFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    B3D_UNKNOWN: _Board3DFormat.ValueType
    B3D_STEP: _Board3DFormat.ValueType
    'Export as STEP AP214.'
    B3D_STEPZ: _Board3DFormat.ValueType
    'Export as compressed STEP.'
    B3D_BREP: _Board3DFormat.ValueType
    'Export as OpenCascade BREP.'
    B3D_XAO: _Board3DFormat.ValueType
    'Export as XAO.'
    B3D_GLB: _Board3DFormat.ValueType
    'Export as binary glTF.'
    B3D_VRML: _Board3DFormat.ValueType
    'Export as VRML.'
    B3D_PLY: _Board3DFormat.ValueType
    'Export as PLY mesh.'
    B3D_STL: _Board3DFormat.ValueType
    'Export as STL mesh.'
    B3D_U3D: _Board3DFormat.ValueType
    'Export as U3D.'
    B3D_PDF: _Board3DFormat.ValueType
    'Export as embedded 3D PDF.'

class Board3DFormat(_Board3DFormat, metaclass=_Board3DFormatEnumTypeWrapper):
    """Output format for board 3D export jobs."""
B3D_UNKNOWN: Board3DFormat.ValueType
B3D_STEP: Board3DFormat.ValueType
'Export as STEP AP214.'
B3D_STEPZ: Board3DFormat.ValueType
'Export as compressed STEP.'
B3D_BREP: Board3DFormat.ValueType
'Export as OpenCascade BREP.'
B3D_XAO: Board3DFormat.ValueType
'Export as XAO.'
B3D_GLB: Board3DFormat.ValueType
'Export as binary glTF.'
B3D_VRML: Board3DFormat.ValueType
'Export as VRML.'
B3D_PLY: Board3DFormat.ValueType
'Export as PLY mesh.'
B3D_STL: Board3DFormat.ValueType
'Export as STL mesh.'
B3D_U3D: Board3DFormat.ValueType
'Export as U3D.'
B3D_PDF: Board3DFormat.ValueType
'Export as embedded 3D PDF.'
global___Board3DFormat = Board3DFormat

class _RenderFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RenderFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RenderFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RF_UNKNOWN: _RenderFormat.ValueType
    RF_PNG: _RenderFormat.ValueType
    RF_JPEG: _RenderFormat.ValueType

class RenderFormat(_RenderFormat, metaclass=_RenderFormatEnumTypeWrapper):
    ...
RF_UNKNOWN: RenderFormat.ValueType
RF_PNG: RenderFormat.ValueType
RF_JPEG: RenderFormat.ValueType
global___RenderFormat = RenderFormat

class _RenderQuality:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RenderQualityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RenderQuality.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RQ_UNKNOWN: _RenderQuality.ValueType
    RQ_BASIC: _RenderQuality.ValueType
    'Basic quality preset.'
    RQ_HIGH: _RenderQuality.ValueType
    'High quality preset.'
    RQ_USER: _RenderQuality.ValueType
    'User-defined quality options.'
    RQ_JOB_SETTINGS: _RenderQuality.ValueType
    'Use quality from job/display settings.'

class RenderQuality(_RenderQuality, metaclass=_RenderQualityEnumTypeWrapper):
    """Rendering quality preset selection"""
RQ_UNKNOWN: RenderQuality.ValueType
RQ_BASIC: RenderQuality.ValueType
'Basic quality preset.'
RQ_HIGH: RenderQuality.ValueType
'High quality preset.'
RQ_USER: RenderQuality.ValueType
'User-defined quality options.'
RQ_JOB_SETTINGS: RenderQuality.ValueType
'Use quality from job/display settings.'
global___RenderQuality = RenderQuality

class _RenderBackgroundStyle:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RenderBackgroundStyleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RenderBackgroundStyle.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RBS_UNKNOWN: _RenderBackgroundStyle.ValueType
    RBS_DEFAULT: _RenderBackgroundStyle.ValueType
    'Use renderer default background behavior.'
    RBS_TRANSPARENT: _RenderBackgroundStyle.ValueType
    'Transparent background.'
    RBS_OPAQUE: _RenderBackgroundStyle.ValueType
    'Opaque background.'

class RenderBackgroundStyle(_RenderBackgroundStyle, metaclass=_RenderBackgroundStyleEnumTypeWrapper):
    """Background style for rendered board snapshots"""
RBS_UNKNOWN: RenderBackgroundStyle.ValueType
RBS_DEFAULT: RenderBackgroundStyle.ValueType
'Use renderer default background behavior.'
RBS_TRANSPARENT: RenderBackgroundStyle.ValueType
'Transparent background.'
RBS_OPAQUE: RenderBackgroundStyle.ValueType
'Opaque background.'
global___RenderBackgroundStyle = RenderBackgroundStyle

class _RenderSide:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RenderSideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RenderSide.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RS_UNKNOWN: _RenderSide.ValueType
    RS_TOP: _RenderSide.ValueType
    RS_BOTTOM: _RenderSide.ValueType
    RS_LEFT: _RenderSide.ValueType
    RS_RIGHT: _RenderSide.ValueType
    RS_FRONT: _RenderSide.ValueType
    RS_BACK: _RenderSide.ValueType

class RenderSide(_RenderSide, metaclass=_RenderSideEnumTypeWrapper):
    """Camera direction for rendered board snapshots"""
RS_UNKNOWN: RenderSide.ValueType
RS_TOP: RenderSide.ValueType
RS_BOTTOM: RenderSide.ValueType
RS_LEFT: RenderSide.ValueType
RS_RIGHT: RenderSide.ValueType
RS_FRONT: RenderSide.ValueType
RS_BACK: RenderSide.ValueType
global___RenderSide = RenderSide

class _BoardJobPaginationMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BoardJobPaginationModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BoardJobPaginationMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BJPM_UNKNOWN: _BoardJobPaginationMode.ValueType
    BJPM_ALL_LAYERS_ONE_PAGE: _BoardJobPaginationMode.ValueType
    'Put all selected layers on one page/canvas in a single output file.'
    BJPM_EACH_LAYER_OWN_PAGE: _BoardJobPaginationMode.ValueType
    'Put each selected layer on its own page inside a single output file.'
    BJPM_EACH_LAYER_OWN_FILE: _BoardJobPaginationMode.ValueType
    'Generate one output file per selected layer.'

class BoardJobPaginationMode(_BoardJobPaginationMode, metaclass=_BoardJobPaginationModeEnumTypeWrapper):
    """Shared pagination/output grouping mode for board plot/export jobs."""
BJPM_UNKNOWN: BoardJobPaginationMode.ValueType
BJPM_ALL_LAYERS_ONE_PAGE: BoardJobPaginationMode.ValueType
'Put all selected layers on one page/canvas in a single output file.'
BJPM_EACH_LAYER_OWN_PAGE: BoardJobPaginationMode.ValueType
'Put each selected layer on its own page inside a single output file.'
BJPM_EACH_LAYER_OWN_FILE: BoardJobPaginationMode.ValueType
'Generate one output file per selected layer.'
global___BoardJobPaginationMode = BoardJobPaginationMode

class _DrillFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DF_UNKNOWN: _DrillFormat.ValueType
    DF_EXCELLON: _DrillFormat.ValueType
    DF_GERBER: _DrillFormat.ValueType

class DrillFormat(_DrillFormat, metaclass=_DrillFormatEnumTypeWrapper):
    ...
DF_UNKNOWN: DrillFormat.ValueType
DF_EXCELLON: DrillFormat.ValueType
DF_GERBER: DrillFormat.ValueType
global___DrillFormat = DrillFormat

class _DrillOrigin:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillOriginEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillOrigin.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DO_UNKNOWN: _DrillOrigin.ValueType
    DO_ABSOLUTE: _DrillOrigin.ValueType
    DO_PLOT: _DrillOrigin.ValueType

class DrillOrigin(_DrillOrigin, metaclass=_DrillOriginEnumTypeWrapper):
    ...
DO_UNKNOWN: DrillOrigin.ValueType
DO_ABSOLUTE: DrillOrigin.ValueType
DO_PLOT: DrillOrigin.ValueType
global___DrillOrigin = DrillOrigin

class _DrillZerosFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillZerosFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillZerosFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DZF_UNKNOWN: _DrillZerosFormat.ValueType
    DZF_DECIMAL: _DrillZerosFormat.ValueType
    DZF_SUPPRESS_LEADING: _DrillZerosFormat.ValueType
    DZF_SUPPRESS_TRAILING: _DrillZerosFormat.ValueType
    DZF_KEEP_ZEROS: _DrillZerosFormat.ValueType

class DrillZerosFormat(_DrillZerosFormat, metaclass=_DrillZerosFormatEnumTypeWrapper):
    ...
DZF_UNKNOWN: DrillZerosFormat.ValueType
DZF_DECIMAL: DrillZerosFormat.ValueType
DZF_SUPPRESS_LEADING: DrillZerosFormat.ValueType
DZF_SUPPRESS_TRAILING: DrillZerosFormat.ValueType
DZF_KEEP_ZEROS: DrillZerosFormat.ValueType
global___DrillZerosFormat = DrillZerosFormat

class _DrillMapFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillMapFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillMapFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DMF_UNKNOWN: _DrillMapFormat.ValueType
    DMF_POSTSCRIPT: _DrillMapFormat.ValueType
    DMF_GERBER_X2: _DrillMapFormat.ValueType
    DMF_DXF: _DrillMapFormat.ValueType
    DMF_SVG: _DrillMapFormat.ValueType
    DMF_PDF: _DrillMapFormat.ValueType

class DrillMapFormat(_DrillMapFormat, metaclass=_DrillMapFormatEnumTypeWrapper):
    ...
DMF_UNKNOWN: DrillMapFormat.ValueType
DMF_POSTSCRIPT: DrillMapFormat.ValueType
DMF_GERBER_X2: DrillMapFormat.ValueType
DMF_DXF: DrillMapFormat.ValueType
DMF_SVG: DrillMapFormat.ValueType
DMF_PDF: DrillMapFormat.ValueType
global___DrillMapFormat = DrillMapFormat

class _DrillGerberPrecision:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillGerberPrecisionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillGerberPrecision.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DGP_UNKNOWN: _DrillGerberPrecision.ValueType
    DGP_4_5: _DrillGerberPrecision.ValueType
    DGP_4_6: _DrillGerberPrecision.ValueType

class DrillGerberPrecision(_DrillGerberPrecision, metaclass=_DrillGerberPrecisionEnumTypeWrapper):
    """Gerber drill numeric precision (format is always 4.x for drill outputs)."""
DGP_UNKNOWN: DrillGerberPrecision.ValueType
DGP_4_5: DrillGerberPrecision.ValueType
DGP_4_6: DrillGerberPrecision.ValueType
global___DrillGerberPrecision = DrillGerberPrecision

class _DrillReportFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrillReportFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrillReportFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DRF_UNKNOWN: _DrillReportFormat.ValueType
    DRF_STANDARD: _DrillReportFormat.ValueType
    'KiCad text drill report'

class DrillReportFormat(_DrillReportFormat, metaclass=_DrillReportFormatEnumTypeWrapper):
    """What format to export drill reports in (only one supported so far...)"""
DRF_UNKNOWN: DrillReportFormat.ValueType
DRF_STANDARD: DrillReportFormat.ValueType
'KiCad text drill report'
global___DrillReportFormat = DrillReportFormat

class _PositionSide:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PositionSideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PositionSide.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PS_UNKNOWN: _PositionSide.ValueType
    PS_FRONT: _PositionSide.ValueType
    'Front side only.'
    PS_BACK: _PositionSide.ValueType
    'Back side only.'
    PS_BOTH: _PositionSide.ValueType
    'Both front and back sides.'

class PositionSide(_PositionSide, metaclass=_PositionSideEnumTypeWrapper):
    """Which board side(s) to include in position file output."""
PS_UNKNOWN: PositionSide.ValueType
PS_FRONT: PositionSide.ValueType
'Front side only.'
PS_BACK: PositionSide.ValueType
'Back side only.'
PS_BOTH: PositionSide.ValueType
'Both front and back sides.'
global___PositionSide = PositionSide

class _PositionFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PositionFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PositionFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PF_UNKNOWN: _PositionFormat.ValueType
    PF_ASCII: _PositionFormat.ValueType
    PF_CSV: _PositionFormat.ValueType
    PF_GERBER: _PositionFormat.ValueType

class PositionFormat(_PositionFormat, metaclass=_PositionFormatEnumTypeWrapper):
    """Unit system used for position file coordinates"""
PF_UNKNOWN: PositionFormat.ValueType
PF_ASCII: PositionFormat.ValueType
PF_CSV: PositionFormat.ValueType
PF_GERBER: PositionFormat.ValueType
global___PositionFormat = PositionFormat

class _Ipc2581Version:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _Ipc2581VersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Ipc2581Version.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IPC2581V_UNKNOWN: _Ipc2581Version.ValueType
    IPC2581V_B: _Ipc2581Version.ValueType
    IPC2581V_C: _Ipc2581Version.ValueType

class Ipc2581Version(_Ipc2581Version, metaclass=_Ipc2581VersionEnumTypeWrapper):
    ...
IPC2581V_UNKNOWN: Ipc2581Version.ValueType
IPC2581V_B: Ipc2581Version.ValueType
IPC2581V_C: Ipc2581Version.ValueType
global___Ipc2581Version = Ipc2581Version

class _OdbCompression:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OdbCompressionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OdbCompression.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ODBC_UNKNOWN: _OdbCompression.ValueType
    ODBC_NONE: _OdbCompression.ValueType
    'Uncompressed ODB++ folder structure.'
    ODBC_ZIP: _OdbCompression.ValueType
    'ZIP archive.'
    ODBC_TGZ: _OdbCompression.ValueType
    'Tar+gzip archive (.tgz).'

class OdbCompression(_OdbCompression, metaclass=_OdbCompressionEnumTypeWrapper):
    """Archive/compression mode used for ODB++ output."""
ODBC_UNKNOWN: OdbCompression.ValueType
ODBC_NONE: OdbCompression.ValueType
'Uncompressed ODB++ folder structure.'
ODBC_ZIP: OdbCompression.ValueType
'ZIP archive.'
ODBC_TGZ: OdbCompression.ValueType
'Tar+gzip archive (.tgz).'
global___OdbCompression = OdbCompression

class _StatsOutputFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatsOutputFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StatsOutputFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SOF_UNKNOWN: _StatsOutputFormat.ValueType
    SOF_REPORT: _StatsOutputFormat.ValueType
    'Human-readable text report.'
    SOF_JSON: _StatsOutputFormat.ValueType
    'JSON structured output.'

class StatsOutputFormat(_StatsOutputFormat, metaclass=_StatsOutputFormatEnumTypeWrapper):
    """Board statistics output format."""
SOF_UNKNOWN: StatsOutputFormat.ValueType
SOF_REPORT: StatsOutputFormat.ValueType
'Human-readable text report.'
SOF_JSON: StatsOutputFormat.ValueType
'JSON structured output.'
global___StatsOutputFormat = StatsOutputFormat

@typing.final
class BoardPlotSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAYERS_FIELD_NUMBER: builtins.int
    COMMON_LAYERS_FIELD_NUMBER: builtins.int
    COLOR_THEME_FIELD_NUMBER: builtins.int
    DRAWING_SHEET_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    MIRROR_FIELD_NUMBER: builtins.int
    BLACK_AND_WHITE_FIELD_NUMBER: builtins.int
    NEGATIVE_FIELD_NUMBER: builtins.int
    SCALE_FIELD_NUMBER: builtins.int
    SKETCH_PADS_ON_FAB_LAYERS_FIELD_NUMBER: builtins.int
    HIDE_DNP_FOOTPRINTS_ON_FAB_LAYERS_FIELD_NUMBER: builtins.int
    SKETCH_DNP_FOOTPRINTS_ON_FAB_LAYERS_FIELD_NUMBER: builtins.int
    CROSSOUT_DNP_FOOTPRINTS_ON_FAB_LAYERS_FIELD_NUMBER: builtins.int
    PLOT_FOOTPRINT_VALUES_FIELD_NUMBER: builtins.int
    PLOT_REFERENCE_DESIGNATORS_FIELD_NUMBER: builtins.int
    PLOT_DRAWING_SHEET_FIELD_NUMBER: builtins.int
    SUBTRACT_SOLDER_MASK_FROM_SILK_FIELD_NUMBER: builtins.int
    PLOT_PAD_NUMBERS_FIELD_NUMBER: builtins.int
    DRILL_MARKS_FIELD_NUMBER: builtins.int
    USE_DRILL_ORIGIN_FIELD_NUMBER: builtins.int
    CHECK_ZONES_BEFORE_PLOT_FIELD_NUMBER: builtins.int
    color_theme: builtins.str
    drawing_sheet: builtins.str
    variant: builtins.str
    mirror: builtins.bool
    black_and_white: builtins.bool
    negative: builtins.bool
    scale: builtins.float
    sketch_pads_on_fab_layers: builtins.bool
    hide_dnp_footprints_on_fab_layers: builtins.bool
    sketch_dnp_footprints_on_fab_layers: builtins.bool
    crossout_dnp_footprints_on_fab_layers: builtins.bool
    plot_footprint_values: builtins.bool
    plot_reference_designators: builtins.bool
    plot_drawing_sheet: builtins.bool
    subtract_solder_mask_from_silk: builtins.bool
    plot_pad_numbers: builtins.bool
    drill_marks: global___PlotDrillMarks.ValueType
    use_drill_origin: builtins.bool
    check_zones_before_plot: builtins.bool

    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[board.board_types_pb2.BoardLayer.ValueType]:
        """One or more board layers to export."""

    @property
    def common_layers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[board.board_types_pb2.BoardLayer.ValueType]:
        """Layers to include on all individual layer plots."""

    def __init__(self, *, layers: collections.abc.Iterable[board.board_types_pb2.BoardLayer.ValueType] | None=..., common_layers: collections.abc.Iterable[board.board_types_pb2.BoardLayer.ValueType] | None=..., color_theme: builtins.str=..., drawing_sheet: builtins.str=..., variant: builtins.str=..., mirror: builtins.bool=..., black_and_white: builtins.bool=..., negative: builtins.bool=..., scale: builtins.float=..., sketch_pads_on_fab_layers: builtins.bool=..., hide_dnp_footprints_on_fab_layers: builtins.bool=..., sketch_dnp_footprints_on_fab_layers: builtins.bool=..., crossout_dnp_footprints_on_fab_layers: builtins.bool=..., plot_footprint_values: builtins.bool=..., plot_reference_designators: builtins.bool=..., plot_drawing_sheet: builtins.bool=..., subtract_solder_mask_from_silk: builtins.bool=..., plot_pad_numbers: builtins.bool=..., drill_marks: global___PlotDrillMarks.ValueType=..., use_drill_origin: builtins.bool=..., check_zones_before_plot: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['black_and_white', b'black_and_white', 'check_zones_before_plot', b'check_zones_before_plot', 'color_theme', b'color_theme', 'common_layers', b'common_layers', 'crossout_dnp_footprints_on_fab_layers', b'crossout_dnp_footprints_on_fab_layers', 'drawing_sheet', b'drawing_sheet', 'drill_marks', b'drill_marks', 'hide_dnp_footprints_on_fab_layers', b'hide_dnp_footprints_on_fab_layers', 'layers', b'layers', 'mirror', b'mirror', 'negative', b'negative', 'plot_drawing_sheet', b'plot_drawing_sheet', 'plot_footprint_values', b'plot_footprint_values', 'plot_pad_numbers', b'plot_pad_numbers', 'plot_reference_designators', b'plot_reference_designators', 'scale', b'scale', 'sketch_dnp_footprints_on_fab_layers', b'sketch_dnp_footprints_on_fab_layers', 'sketch_pads_on_fab_layers', b'sketch_pads_on_fab_layers', 'subtract_solder_mask_from_silk', b'subtract_solder_mask_from_silk', 'use_drill_origin', b'use_drill_origin', 'variant', b'variant']) -> None:
        ...
global___BoardPlotSettings = BoardPlotSettings

@typing.final
class RunBoardJobExport3D(google.protobuf.message.Message):
    """Exports a board as a 3D model file.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    NET_FILTER_FIELD_NUMBER: builtins.int
    COMPONENT_FILTER_FIELD_NUMBER: builtins.int
    HAS_USER_ORIGIN_FIELD_NUMBER: builtins.int
    ORIGIN_FIELD_NUMBER: builtins.int
    OVERWRITE_FIELD_NUMBER: builtins.int
    USE_GRID_ORIGIN_FIELD_NUMBER: builtins.int
    USE_DRILL_ORIGIN_FIELD_NUMBER: builtins.int
    USE_DEFINED_ORIGIN_FIELD_NUMBER: builtins.int
    USE_PCB_CENTER_ORIGIN_FIELD_NUMBER: builtins.int
    INCLUDE_UNSPECIFIED_FIELD_NUMBER: builtins.int
    INCLUDE_DNP_FIELD_NUMBER: builtins.int
    SUBSTITUTE_MODELS_FIELD_NUMBER: builtins.int
    BOARD_OUTLINES_CHAINING_EPSILON_FIELD_NUMBER: builtins.int
    BOARD_ONLY_FIELD_NUMBER: builtins.int
    CUT_VIAS_IN_BODY_FIELD_NUMBER: builtins.int
    EXPORT_BOARD_BODY_FIELD_NUMBER: builtins.int
    EXPORT_COMPONENTS_FIELD_NUMBER: builtins.int
    EXPORT_TRACKS_AND_VIAS_FIELD_NUMBER: builtins.int
    EXPORT_PADS_FIELD_NUMBER: builtins.int
    EXPORT_ZONES_FIELD_NUMBER: builtins.int
    EXPORT_INNER_COPPER_FIELD_NUMBER: builtins.int
    EXPORT_SILKSCREEN_FIELD_NUMBER: builtins.int
    EXPORT_SOLDERMASK_FIELD_NUMBER: builtins.int
    FUSE_SHAPES_FIELD_NUMBER: builtins.int
    FILL_ALL_VIAS_FIELD_NUMBER: builtins.int
    OPTIMIZE_STEP_FIELD_NUMBER: builtins.int
    EXTRA_PAD_THICKNESS_FIELD_NUMBER: builtins.int
    VRML_UNITS_FIELD_NUMBER: builtins.int
    VRML_MODEL_DIR_FIELD_NUMBER: builtins.int
    VRML_RELATIVE_PATHS_FIELD_NUMBER: builtins.int
    variant: builtins.str
    format: global___Board3DFormat.ValueType
    net_filter: builtins.str
    component_filter: builtins.str
    has_user_origin: builtins.bool
    overwrite: builtins.bool
    use_grid_origin: builtins.bool
    use_drill_origin: builtins.bool
    use_defined_origin: builtins.bool
    use_pcb_center_origin: builtins.bool
    include_unspecified: builtins.bool
    include_dnp: builtins.bool
    substitute_models: builtins.bool
    board_outlines_chaining_epsilon: builtins.float
    board_only: builtins.bool
    cut_vias_in_body: builtins.bool
    export_board_body: builtins.bool
    export_components: builtins.bool
    export_tracks_and_vias: builtins.bool
    export_pads: builtins.bool
    export_zones: builtins.bool
    export_inner_copper: builtins.bool
    export_silkscreen: builtins.bool
    export_soldermask: builtins.bool
    fuse_shapes: builtins.bool
    fill_all_vias: builtins.bool
    optimize_step: builtins.bool
    extra_pad_thickness: builtins.bool
    vrml_units: common.types.enums_pb2.Units.ValueType
    'Inches, millimeters, meters, or tenths of an inch are accepted'
    vrml_model_dir: builtins.str
    vrml_relative_paths: builtins.bool

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def origin(self) -> common.types.base_types_pb2.Vector2:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., variant: builtins.str=..., format: global___Board3DFormat.ValueType=..., net_filter: builtins.str=..., component_filter: builtins.str=..., has_user_origin: builtins.bool=..., origin: common.types.base_types_pb2.Vector2 | None=..., overwrite: builtins.bool=..., use_grid_origin: builtins.bool=..., use_drill_origin: builtins.bool=..., use_defined_origin: builtins.bool=..., use_pcb_center_origin: builtins.bool=..., include_unspecified: builtins.bool=..., include_dnp: builtins.bool=..., substitute_models: builtins.bool=..., board_outlines_chaining_epsilon: builtins.float=..., board_only: builtins.bool=..., cut_vias_in_body: builtins.bool=..., export_board_body: builtins.bool=..., export_components: builtins.bool=..., export_tracks_and_vias: builtins.bool=..., export_pads: builtins.bool=..., export_zones: builtins.bool=..., export_inner_copper: builtins.bool=..., export_silkscreen: builtins.bool=..., export_soldermask: builtins.bool=..., fuse_shapes: builtins.bool=..., fill_all_vias: builtins.bool=..., optimize_step: builtins.bool=..., extra_pad_thickness: builtins.bool=..., vrml_units: common.types.enums_pb2.Units.ValueType=..., vrml_model_dir: builtins.str=..., vrml_relative_paths: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'origin', b'origin']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['board_only', b'board_only', 'board_outlines_chaining_epsilon', b'board_outlines_chaining_epsilon', 'component_filter', b'component_filter', 'cut_vias_in_body', b'cut_vias_in_body', 'export_board_body', b'export_board_body', 'export_components', b'export_components', 'export_inner_copper', b'export_inner_copper', 'export_pads', b'export_pads', 'export_silkscreen', b'export_silkscreen', 'export_soldermask', b'export_soldermask', 'export_tracks_and_vias', b'export_tracks_and_vias', 'export_zones', b'export_zones', 'extra_pad_thickness', b'extra_pad_thickness', 'fill_all_vias', b'fill_all_vias', 'format', b'format', 'fuse_shapes', b'fuse_shapes', 'has_user_origin', b'has_user_origin', 'include_dnp', b'include_dnp', 'include_unspecified', b'include_unspecified', 'job_settings', b'job_settings', 'net_filter', b'net_filter', 'optimize_step', b'optimize_step', 'origin', b'origin', 'overwrite', b'overwrite', 'substitute_models', b'substitute_models', 'use_defined_origin', b'use_defined_origin', 'use_drill_origin', b'use_drill_origin', 'use_grid_origin', b'use_grid_origin', 'use_pcb_center_origin', b'use_pcb_center_origin', 'variant', b'variant', 'vrml_model_dir', b'vrml_model_dir', 'vrml_relative_paths', b'vrml_relative_paths', 'vrml_units', b'vrml_units']) -> None:
        ...
global___RunBoardJobExport3D = RunBoardJobExport3D

@typing.final
class RunBoardJobExportRender(google.protobuf.message.Message):
    """Exports a raytraced 3D render of a board.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    QUALITY_FIELD_NUMBER: builtins.int
    BACKGROUND_STYLE_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    APPEARANCE_PRESET_FIELD_NUMBER: builtins.int
    USE_BOARD_STACKUP_COLORS_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    ZOOM_FIELD_NUMBER: builtins.int
    PERSPECTIVE_FIELD_NUMBER: builtins.int
    ROTATION_FIELD_NUMBER: builtins.int
    PAN_FIELD_NUMBER: builtins.int
    PIVOT_FIELD_NUMBER: builtins.int
    PROCEDURAL_TEXTURES_FIELD_NUMBER: builtins.int
    FLOOR_FIELD_NUMBER: builtins.int
    ANTI_ALIAS_FIELD_NUMBER: builtins.int
    POST_PROCESS_FIELD_NUMBER: builtins.int
    LIGHT_TOP_INTENSITY_FIELD_NUMBER: builtins.int
    LIGHT_BOTTOM_INTENSITY_FIELD_NUMBER: builtins.int
    LIGHT_CAMERA_INTENSITY_FIELD_NUMBER: builtins.int
    LIGHT_SIDE_INTENSITY_FIELD_NUMBER: builtins.int
    LIGHT_SIDE_ELEVATION_FIELD_NUMBER: builtins.int
    format: global___RenderFormat.ValueType
    quality: global___RenderQuality.ValueType
    background_style: global___RenderBackgroundStyle.ValueType
    width: builtins.int
    height: builtins.int
    appearance_preset: builtins.str
    use_board_stackup_colors: builtins.bool
    side: global___RenderSide.ValueType
    zoom: builtins.float
    perspective: builtins.bool
    procedural_textures: builtins.bool
    floor: builtins.bool
    anti_alias: builtins.bool
    post_process: builtins.bool
    light_side_elevation: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def rotation(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def pan(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def pivot(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def light_top_intensity(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def light_bottom_intensity(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def light_camera_intensity(self) -> common.types.base_types_pb2.Vector3D:
        ...

    @property
    def light_side_intensity(self) -> common.types.base_types_pb2.Vector3D:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., format: global___RenderFormat.ValueType=..., quality: global___RenderQuality.ValueType=..., background_style: global___RenderBackgroundStyle.ValueType=..., width: builtins.int=..., height: builtins.int=..., appearance_preset: builtins.str=..., use_board_stackup_colors: builtins.bool=..., side: global___RenderSide.ValueType=..., zoom: builtins.float=..., perspective: builtins.bool=..., rotation: common.types.base_types_pb2.Vector3D | None=..., pan: common.types.base_types_pb2.Vector3D | None=..., pivot: common.types.base_types_pb2.Vector3D | None=..., procedural_textures: builtins.bool=..., floor: builtins.bool=..., anti_alias: builtins.bool=..., post_process: builtins.bool=..., light_top_intensity: common.types.base_types_pb2.Vector3D | None=..., light_bottom_intensity: common.types.base_types_pb2.Vector3D | None=..., light_camera_intensity: common.types.base_types_pb2.Vector3D | None=..., light_side_intensity: common.types.base_types_pb2.Vector3D | None=..., light_side_elevation: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'light_bottom_intensity', b'light_bottom_intensity', 'light_camera_intensity', b'light_camera_intensity', 'light_side_intensity', b'light_side_intensity', 'light_top_intensity', b'light_top_intensity', 'pan', b'pan', 'pivot', b'pivot', 'rotation', b'rotation']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['anti_alias', b'anti_alias', 'appearance_preset', b'appearance_preset', 'background_style', b'background_style', 'floor', b'floor', 'format', b'format', 'height', b'height', 'job_settings', b'job_settings', 'light_bottom_intensity', b'light_bottom_intensity', 'light_camera_intensity', b'light_camera_intensity', 'light_side_elevation', b'light_side_elevation', 'light_side_intensity', b'light_side_intensity', 'light_top_intensity', b'light_top_intensity', 'pan', b'pan', 'perspective', b'perspective', 'pivot', b'pivot', 'post_process', b'post_process', 'procedural_textures', b'procedural_textures', 'quality', b'quality', 'rotation', b'rotation', 'side', b'side', 'use_board_stackup_colors', b'use_board_stackup_colors', 'width', b'width', 'zoom', b'zoom']) -> None:
        ...
global___RunBoardJobExportRender = RunBoardJobExportRender

@typing.final
class RunBoardJobExportSvg(google.protobuf.message.Message):
    """Plots a board to an SVG file. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int
    FIT_PAGE_TO_BOARD_FIELD_NUMBER: builtins.int
    PRECISION_FIELD_NUMBER: builtins.int
    PAGE_MODE_FIELD_NUMBER: builtins.int
    fit_page_to_board: builtins.bool
    precision: builtins.int
    page_mode: global___BoardJobPaginationMode.ValueType
    'Supports BJPM_ALL_LAYERS_ONE_PAGE and BJPM_EACH_LAYER_OWN_FILE.'

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___BoardPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___BoardPlotSettings | None=..., fit_page_to_board: builtins.bool=..., precision: builtins.int=..., page_mode: global___BoardJobPaginationMode.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['fit_page_to_board', b'fit_page_to_board', 'job_settings', b'job_settings', 'page_mode', b'page_mode', 'plot_settings', b'plot_settings', 'precision', b'precision']) -> None:
        ...
global___RunBoardJobExportSvg = RunBoardJobExportSvg

@typing.final
class RunBoardJobExportDxf(google.protobuf.message.Message):
    """Exports a board to a DXF file. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_GRAPHIC_ITEMS_USING_CONTOURS_FIELD_NUMBER: builtins.int
    POLYGON_MODE_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    PAGE_MODE_FIELD_NUMBER: builtins.int
    plot_graphic_items_using_contours: builtins.bool
    polygon_mode: builtins.bool
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    page_mode: global___BoardJobPaginationMode.ValueType
    'Supports BJPM_ALL_LAYERS_ONE_PAGE and BJPM_EACH_LAYER_OWN_FILE.'

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___BoardPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___BoardPlotSettings | None=..., plot_graphic_items_using_contours: builtins.bool=..., polygon_mode: builtins.bool=..., units: common.types.enums_pb2.Units.ValueType=..., page_mode: global___BoardJobPaginationMode.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings', 'page_mode', b'page_mode', 'plot_graphic_items_using_contours', b'plot_graphic_items_using_contours', 'plot_settings', b'plot_settings', 'polygon_mode', b'polygon_mode', 'units', b'units']) -> None:
        ...
global___RunBoardJobExportDxf = RunBoardJobExportDxf

@typing.final
class RunBoardJobExportPdf(google.protobuf.message.Message):
    """Plots a board to a PDF file. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int
    FRONT_FOOTPRINT_PROPERTY_POPUPS_FIELD_NUMBER: builtins.int
    BACK_FOOTPRINT_PROPERTY_POPUPS_FIELD_NUMBER: builtins.int
    INCLUDE_METADATA_FIELD_NUMBER: builtins.int
    SINGLE_DOCUMENT_FIELD_NUMBER: builtins.int
    PAGE_MODE_FIELD_NUMBER: builtins.int
    BACKGROUND_COLOR_FIELD_NUMBER: builtins.int
    front_footprint_property_popups: builtins.bool
    back_footprint_property_popups: builtins.bool
    include_metadata: builtins.bool
    single_document: builtins.bool
    page_mode: global___BoardJobPaginationMode.ValueType
    background_color: builtins.str

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___BoardPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___BoardPlotSettings | None=..., front_footprint_property_popups: builtins.bool=..., back_footprint_property_popups: builtins.bool=..., include_metadata: builtins.bool=..., single_document: builtins.bool=..., page_mode: global___BoardJobPaginationMode.ValueType=..., background_color: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['back_footprint_property_popups', b'back_footprint_property_popups', 'background_color', b'background_color', 'front_footprint_property_popups', b'front_footprint_property_popups', 'include_metadata', b'include_metadata', 'job_settings', b'job_settings', 'page_mode', b'page_mode', 'plot_settings', b'plot_settings', 'single_document', b'single_document']) -> None:
        ...
global___RunBoardJobExportPdf = RunBoardJobExportPdf

@typing.final
class RunBoardJobExportPs(google.protobuf.message.Message):
    """Plots a board to a PostScript file. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    PLOT_SETTINGS_FIELD_NUMBER: builtins.int
    PAGE_MODE_FIELD_NUMBER: builtins.int
    TRACK_WIDTH_CORRECTION_FIELD_NUMBER: builtins.int
    X_SCALE_ADJUST_FIELD_NUMBER: builtins.int
    Y_SCALE_ADJUST_FIELD_NUMBER: builtins.int
    FORCE_A4_FIELD_NUMBER: builtins.int
    USE_GLOBAL_SETTINGS_FIELD_NUMBER: builtins.int
    page_mode: global___BoardJobPaginationMode.ValueType
    'Supports BJPM_ALL_LAYERS_ONE_PAGE and BJPM_EACH_LAYER_OWN_FILE.'
    track_width_correction: builtins.float
    x_scale_adjust: builtins.float
    y_scale_adjust: builtins.float
    force_a4: builtins.bool
    use_global_settings: builtins.bool

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def plot_settings(self) -> global___BoardPlotSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., plot_settings: global___BoardPlotSettings | None=..., page_mode: global___BoardJobPaginationMode.ValueType=..., track_width_correction: builtins.float=..., x_scale_adjust: builtins.float=..., y_scale_adjust: builtins.float=..., force_a4: builtins.bool=..., use_global_settings: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings', 'plot_settings', b'plot_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['force_a4', b'force_a4', 'job_settings', b'job_settings', 'page_mode', b'page_mode', 'plot_settings', b'plot_settings', 'track_width_correction', b'track_width_correction', 'use_global_settings', b'use_global_settings', 'x_scale_adjust', b'x_scale_adjust', 'y_scale_adjust', b'y_scale_adjust']) -> None:
        ...
global___RunBoardJobExportPs = RunBoardJobExportPs

@typing.final
class RunBoardJobExportGerbers(google.protobuf.message.Message):
    """Plots a board to Gerber files. Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    LAYERS_FIELD_NUMBER: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[board.board_types_pb2.BoardLayer.ValueType]:
        """One or more board layers to export."""

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., layers: collections.abc.Iterable[board.board_types_pb2.BoardLayer.ValueType] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings', 'layers', b'layers']) -> None:
        ...
global___RunBoardJobExportGerbers = RunBoardJobExportGerbers

@typing.final
class ExcellonFormatOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MIRROR_Y_FIELD_NUMBER: builtins.int
    MINIMAL_HEADER_FIELD_NUMBER: builtins.int
    COMBINE_PTH_NPTH_FIELD_NUMBER: builtins.int
    ROUTE_OVAL_HOLES_FIELD_NUMBER: builtins.int
    mirror_y: builtins.bool
    'If true, Y coordinates will be negated in the drill file'
    minimal_header: builtins.bool
    'If true, comments and other optional info will be omitted from the drill file header'
    combine_pth_npth: builtins.bool
    'If true, a single drill file will be created with both PTH and NPTH holes'
    route_oval_holes: builtins.bool
    'If true, will generate a "route" operation instead of "drill" for oval-shaped holes'

    def __init__(self, *, mirror_y: builtins.bool | None=..., minimal_header: builtins.bool | None=..., combine_pth_npth: builtins.bool | None=..., route_oval_holes: builtins.bool | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_combine_pth_npth', b'_combine_pth_npth', '_minimal_header', b'_minimal_header', '_mirror_y', b'_mirror_y', '_route_oval_holes', b'_route_oval_holes', 'combine_pth_npth', b'combine_pth_npth', 'minimal_header', b'minimal_header', 'mirror_y', b'mirror_y', 'route_oval_holes', b'route_oval_holes']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_combine_pth_npth', b'_combine_pth_npth', '_minimal_header', b'_minimal_header', '_mirror_y', b'_mirror_y', '_route_oval_holes', b'_route_oval_holes', 'combine_pth_npth', b'combine_pth_npth', 'minimal_header', b'minimal_header', 'mirror_y', b'mirror_y', 'route_oval_holes', b'route_oval_holes']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_combine_pth_npth', b'_combine_pth_npth']) -> typing.Literal['combine_pth_npth'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_minimal_header', b'_minimal_header']) -> typing.Literal['minimal_header'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_mirror_y', b'_mirror_y']) -> typing.Literal['mirror_y'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_route_oval_holes', b'_route_oval_holes']) -> typing.Literal['route_oval_holes'] | None:
        ...
global___ExcellonFormatOptions = ExcellonFormatOptions

@typing.final
class RunBoardJobExportDrill(google.protobuf.message.Message):
    """Exports NC drill files from a board.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    ORIGIN_FIELD_NUMBER: builtins.int
    ZEROS_FORMAT_FIELD_NUMBER: builtins.int
    EXCELLON_FIELD_NUMBER: builtins.int
    MAP_FORMAT_FIELD_NUMBER: builtins.int
    GERBER_PRECISION_FIELD_NUMBER: builtins.int
    GERBER_GENERATE_TENTING_FIELD_NUMBER: builtins.int
    REPORT_FORMAT_FIELD_NUMBER: builtins.int
    REPORT_FILENAME_FIELD_NUMBER: builtins.int
    format: global___DrillFormat.ValueType
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    origin: global___DrillOrigin.ValueType
    zeros_format: global___DrillZerosFormat.ValueType
    map_format: global___DrillMapFormat.ValueType
    'Set to a valid value to generate a drill map.  Leave unset for no drill map.'
    gerber_precision: global___DrillGerberPrecision.ValueType
    'When generating drill files in Gerber format, the precision to use for coordinates'
    gerber_generate_tenting: builtins.bool
    'When generating drill files in Gerber format, will create additional gerbers specifying\n    front and back tenting locations for tented pads and vias.\n    '
    report_format: global___DrillReportFormat.ValueType
    'Set to a valid value to generate a drill report.  Leave unset for no report.'
    report_filename: builtins.str

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    @property
    def excellon(self) -> global___ExcellonFormatOptions:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., format: global___DrillFormat.ValueType=..., units: common.types.enums_pb2.Units.ValueType=..., origin: global___DrillOrigin.ValueType=..., zeros_format: global___DrillZerosFormat.ValueType=..., excellon: global___ExcellonFormatOptions | None=..., map_format: global___DrillMapFormat.ValueType=..., gerber_precision: global___DrillGerberPrecision.ValueType=..., gerber_generate_tenting: builtins.bool | None=..., report_format: global___DrillReportFormat.ValueType=..., report_filename: builtins.str | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_gerber_generate_tenting', b'_gerber_generate_tenting', '_report_filename', b'_report_filename', 'excellon', b'excellon', 'gerber_generate_tenting', b'gerber_generate_tenting', 'job_settings', b'job_settings', 'report_filename', b'report_filename']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_gerber_generate_tenting', b'_gerber_generate_tenting', '_report_filename', b'_report_filename', 'excellon', b'excellon', 'format', b'format', 'gerber_generate_tenting', b'gerber_generate_tenting', 'gerber_precision', b'gerber_precision', 'job_settings', b'job_settings', 'map_format', b'map_format', 'origin', b'origin', 'report_filename', b'report_filename', 'report_format', b'report_format', 'units', b'units', 'zeros_format', b'zeros_format']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_gerber_generate_tenting', b'_gerber_generate_tenting']) -> typing.Literal['gerber_generate_tenting'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_report_filename', b'_report_filename']) -> typing.Literal['report_filename'] | None:
        ...
global___RunBoardJobExportDrill = RunBoardJobExportDrill

@typing.final
class RunBoardJobExportPosition(google.protobuf.message.Message):
    """Exports position files (pick-and-place centroids) from a board.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    USE_DRILL_PLACE_FILE_ORIGIN_FIELD_NUMBER: builtins.int
    SMD_ONLY_FIELD_NUMBER: builtins.int
    EXCLUDE_FOOTPRINTS_WITH_TH_FIELD_NUMBER: builtins.int
    EXCLUDE_DNP_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_BOM_FIELD_NUMBER: builtins.int
    NEGATE_BOTTOM_X_FIELD_NUMBER: builtins.int
    SINGLE_FILE_FIELD_NUMBER: builtins.int
    NAKED_FILENAME_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    INCLUDE_BOARD_EDGE_FOR_GERBER_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    use_drill_place_file_origin: builtins.bool
    smd_only: builtins.bool
    exclude_footprints_with_th: builtins.bool
    exclude_dnp: builtins.bool
    exclude_from_bom: builtins.bool
    negate_bottom_x: builtins.bool
    single_file: builtins.bool
    naked_filename: builtins.bool
    side: global___PositionSide.ValueType
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    format: global___PositionFormat.ValueType
    include_board_edge_for_gerber: builtins.bool
    variant: builtins.str

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., use_drill_place_file_origin: builtins.bool | None=..., smd_only: builtins.bool=..., exclude_footprints_with_th: builtins.bool=..., exclude_dnp: builtins.bool=..., exclude_from_bom: builtins.bool=..., negate_bottom_x: builtins.bool=..., single_file: builtins.bool=..., naked_filename: builtins.bool=..., side: global___PositionSide.ValueType=..., units: common.types.enums_pb2.Units.ValueType=..., format: global___PositionFormat.ValueType=..., include_board_edge_for_gerber: builtins.bool | None=..., variant: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_include_board_edge_for_gerber', b'_include_board_edge_for_gerber', '_use_drill_place_file_origin', b'_use_drill_place_file_origin', 'include_board_edge_for_gerber', b'include_board_edge_for_gerber', 'job_settings', b'job_settings', 'use_drill_place_file_origin', b'use_drill_place_file_origin']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_include_board_edge_for_gerber', b'_include_board_edge_for_gerber', '_use_drill_place_file_origin', b'_use_drill_place_file_origin', 'exclude_dnp', b'exclude_dnp', 'exclude_footprints_with_th', b'exclude_footprints_with_th', 'exclude_from_bom', b'exclude_from_bom', 'format', b'format', 'include_board_edge_for_gerber', b'include_board_edge_for_gerber', 'job_settings', b'job_settings', 'naked_filename', b'naked_filename', 'negate_bottom_x', b'negate_bottom_x', 'side', b'side', 'single_file', b'single_file', 'smd_only', b'smd_only', 'units', b'units', 'use_drill_place_file_origin', b'use_drill_place_file_origin', 'variant', b'variant']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_include_board_edge_for_gerber', b'_include_board_edge_for_gerber']) -> typing.Literal['include_board_edge_for_gerber'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_use_drill_place_file_origin', b'_use_drill_place_file_origin']) -> typing.Literal['use_drill_place_file_origin'] | None:
        ...
global___RunBoardJobExportPosition = RunBoardJobExportPosition

@typing.final
class RunBoardJobExportGencad(google.protobuf.message.Message):
    """Exports a board to Gencad format.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FLIP_BOTTOM_PADS_FIELD_NUMBER: builtins.int
    USE_INDIVIDUAL_SHAPES_FIELD_NUMBER: builtins.int
    STORE_ORIGIN_COORDS_FIELD_NUMBER: builtins.int
    USE_DRILL_ORIGIN_FIELD_NUMBER: builtins.int
    USE_UNIQUE_PINS_FIELD_NUMBER: builtins.int
    flip_bottom_pads: builtins.bool
    use_individual_shapes: builtins.bool
    store_origin_coords: builtins.bool
    use_drill_origin: builtins.bool
    use_unique_pins: builtins.bool

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., flip_bottom_pads: builtins.bool=..., use_individual_shapes: builtins.bool=..., store_origin_coords: builtins.bool=..., use_drill_origin: builtins.bool=..., use_unique_pins: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['flip_bottom_pads', b'flip_bottom_pads', 'job_settings', b'job_settings', 'store_origin_coords', b'store_origin_coords', 'use_drill_origin', b'use_drill_origin', 'use_individual_shapes', b'use_individual_shapes', 'use_unique_pins', b'use_unique_pins']) -> None:
        ...
global___RunBoardJobExportGencad = RunBoardJobExportGencad

@typing.final
class RunBoardJobExportIpc2581(google.protobuf.message.Message):
    """Exports a board to IPC-2581 format.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    DRAWING_SHEET_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PRECISION_FIELD_NUMBER: builtins.int
    COMPRESS_FIELD_NUMBER: builtins.int
    INTERNAL_ID_COLUMN_FIELD_NUMBER: builtins.int
    MANUFACTURER_PART_NUMBER_COLUMN_FIELD_NUMBER: builtins.int
    MANUFACTURER_COLUMN_FIELD_NUMBER: builtins.int
    DISTRIBUTOR_PART_NUMBER_COLUMN_FIELD_NUMBER: builtins.int
    DISTRIBUTOR_COLUMN_FIELD_NUMBER: builtins.int
    BOM_REVISION_FIELD_NUMBER: builtins.int
    drawing_sheet: builtins.str
    variant: builtins.str
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    version: global___Ipc2581Version.ValueType
    precision: builtins.int
    compress: builtins.bool
    internal_id_column: builtins.str
    manufacturer_part_number_column: builtins.str
    manufacturer_column: builtins.str
    distributor_part_number_column: builtins.str
    distributor_column: builtins.str
    bom_revision: builtins.str

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., drawing_sheet: builtins.str=..., variant: builtins.str=..., units: common.types.enums_pb2.Units.ValueType=..., version: global___Ipc2581Version.ValueType=..., precision: builtins.int | None=..., compress: builtins.bool=..., internal_id_column: builtins.str=..., manufacturer_part_number_column: builtins.str=..., manufacturer_column: builtins.str=..., distributor_part_number_column: builtins.str=..., distributor_column: builtins.str=..., bom_revision: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_precision', b'_precision', 'job_settings', b'job_settings', 'precision', b'precision']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_precision', b'_precision', 'bom_revision', b'bom_revision', 'compress', b'compress', 'distributor_column', b'distributor_column', 'distributor_part_number_column', b'distributor_part_number_column', 'drawing_sheet', b'drawing_sheet', 'internal_id_column', b'internal_id_column', 'job_settings', b'job_settings', 'manufacturer_column', b'manufacturer_column', 'manufacturer_part_number_column', b'manufacturer_part_number_column', 'precision', b'precision', 'units', b'units', 'variant', b'variant', 'version', b'version']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_precision', b'_precision']) -> typing.Literal['precision'] | None:
        ...
global___RunBoardJobExportIpc2581 = RunBoardJobExportIpc2581

@typing.final
class RunBoardJobExportIpcD356(google.protobuf.message.Message):
    """Exports a board netlist in IPC-D-356 format.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> None:
        ...
global___RunBoardJobExportIpcD356 = RunBoardJobExportIpcD356

@typing.final
class RunBoardJobExportODB(google.protobuf.message.Message):
    """Exports a board to ODB++ format.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    DRAWING_SHEET_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    PRECISION_FIELD_NUMBER: builtins.int
    COMPRESSION_FIELD_NUMBER: builtins.int
    drawing_sheet: builtins.str
    variant: builtins.str
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    precision: builtins.int
    compression: global___OdbCompression.ValueType

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., drawing_sheet: builtins.str=..., variant: builtins.str=..., units: common.types.enums_pb2.Units.ValueType=..., precision: builtins.int | None=..., compression: global___OdbCompression.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_precision', b'_precision', 'job_settings', b'job_settings', 'precision', b'precision']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_precision', b'_precision', 'compression', b'compression', 'drawing_sheet', b'drawing_sheet', 'job_settings', b'job_settings', 'precision', b'precision', 'units', b'units', 'variant', b'variant']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_precision', b'_precision']) -> typing.Literal['precision'] | None:
        ...
global___RunBoardJobExportODB = RunBoardJobExportODB

@typing.final
class RunBoardJobExportStats(google.protobuf.message.Message):
    """Exports board statistics.  Returns RunJobResponse."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_SETTINGS_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    EXCLUDE_FOOTPRINTS_WITHOUT_PADS_FIELD_NUMBER: builtins.int
    SUBTRACT_HOLES_FROM_BOARD_AREA_FIELD_NUMBER: builtins.int
    SUBTRACT_HOLES_FROM_COPPER_AREAS_FIELD_NUMBER: builtins.int
    format: global___StatsOutputFormat.ValueType
    units: common.types.enums_pb2.Units.ValueType
    'Inches or millimeters are accepted'
    exclude_footprints_without_pads: builtins.bool
    subtract_holes_from_board_area: builtins.bool
    subtract_holes_from_copper_areas: builtins.bool

    @property
    def job_settings(self) -> common.types.jobs_pb2.RunJobSettings:
        ...

    def __init__(self, *, job_settings: common.types.jobs_pb2.RunJobSettings | None=..., format: global___StatsOutputFormat.ValueType=..., units: common.types.enums_pb2.Units.ValueType=..., exclude_footprints_without_pads: builtins.bool=..., subtract_holes_from_board_area: builtins.bool=..., subtract_holes_from_copper_areas: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['job_settings', b'job_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['exclude_footprints_without_pads', b'exclude_footprints_without_pads', 'format', b'format', 'job_settings', b'job_settings', 'subtract_holes_from_board_area', b'subtract_holes_from_board_area', 'subtract_holes_from_copper_areas', b'subtract_holes_from_copper_areas', 'units', b'units']) -> None:
        ...
global___RunBoardJobExportStats = RunBoardJobExportStats