"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

enums.proto
Includes protobuf versions of common KiCad enums
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _KiCadObjectType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _KiCadObjectTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_KiCadObjectType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    KOT_UNKNOWN: _KiCadObjectType.ValueType
    KOT_PCB_FOOTPRINT: _KiCadObjectType.ValueType
    KOT_PCB_PAD: _KiCadObjectType.ValueType
    KOT_PCB_SHAPE: _KiCadObjectType.ValueType
    KOT_PCB_REFERENCE_IMAGE: _KiCadObjectType.ValueType
    KOT_PCB_FIELD: _KiCadObjectType.ValueType
    KOT_PCB_GENERATOR: _KiCadObjectType.ValueType
    KOT_PCB_TEXT: _KiCadObjectType.ValueType
    KOT_PCB_TEXTBOX: _KiCadObjectType.ValueType
    KOT_PCB_TABLE: _KiCadObjectType.ValueType
    KOT_PCB_TABLECELL: _KiCadObjectType.ValueType
    KOT_PCB_TRACE: _KiCadObjectType.ValueType
    KOT_PCB_VIA: _KiCadObjectType.ValueType
    KOT_PCB_ARC: _KiCadObjectType.ValueType
    KOT_PCB_MARKER: _KiCadObjectType.ValueType
    KOT_PCB_DIMENSION: _KiCadObjectType.ValueType
    KOT_PCB_ZONE: _KiCadObjectType.ValueType
    KOT_PCB_GROUP: _KiCadObjectType.ValueType
    KOT_SCH_MARKER: _KiCadObjectType.ValueType
    KOT_SCH_JUNCTION: _KiCadObjectType.ValueType
    KOT_SCH_NO_CONNECT: _KiCadObjectType.ValueType
    KOT_SCH_BUS_WIRE_ENTRY: _KiCadObjectType.ValueType
    KOT_SCH_BUS_BUS_ENTRY: _KiCadObjectType.ValueType
    KOT_SCH_LINE: _KiCadObjectType.ValueType
    KOT_SCH_SHAPE: _KiCadObjectType.ValueType
    KOT_SCH_BITMAP: _KiCadObjectType.ValueType
    KOT_SCH_TEXTBOX: _KiCadObjectType.ValueType
    KOT_SCH_TEXT: _KiCadObjectType.ValueType
    KOT_SCH_TABLE: _KiCadObjectType.ValueType
    KOT_SCH_TABLECELL: _KiCadObjectType.ValueType
    KOT_SCH_LABEL: _KiCadObjectType.ValueType
    KOT_SCH_GLOBAL_LABEL: _KiCadObjectType.ValueType
    KOT_SCH_HIER_LABEL: _KiCadObjectType.ValueType
    KOT_SCH_DIRECTIVE_LABEL: _KiCadObjectType.ValueType
    KOT_SCH_FIELD: _KiCadObjectType.ValueType
    KOT_SCH_SYMBOL: _KiCadObjectType.ValueType
    KOT_SCH_SHEET_PIN: _KiCadObjectType.ValueType
    KOT_SCH_SHEET: _KiCadObjectType.ValueType
    KOT_SCH_PIN: _KiCadObjectType.ValueType
    KOT_LIB_SYMBOL: _KiCadObjectType.ValueType
    ' KOT_LIB_SHAPE = 40;\n     KOT_LIB_TEXT = 41;\n     KOT_LIB_TEXTBOX = 42;\n     KOT_LIB_PIN = 43;\n     KOT_LIB_FIELD = 44;\n    '
    KOT_WSG_LINE: _KiCadObjectType.ValueType
    KOT_WSG_RECT: _KiCadObjectType.ValueType
    KOT_WSG_POLY: _KiCadObjectType.ValueType
    KOT_WSG_TEXT: _KiCadObjectType.ValueType
    KOT_WSG_BITMAP: _KiCadObjectType.ValueType
    KOT_WSG_PAGE: _KiCadObjectType.ValueType
    KOT_SCH_GROUP: _KiCadObjectType.ValueType
    KOT_PCB_BARCODE: _KiCadObjectType.ValueType

class KiCadObjectType(_KiCadObjectType, metaclass=_KiCadObjectTypeEnumTypeWrapper):
    """The set of object types (from KICAD_T) that are exposed to the API."""
KOT_UNKNOWN: KiCadObjectType.ValueType
KOT_PCB_FOOTPRINT: KiCadObjectType.ValueType
KOT_PCB_PAD: KiCadObjectType.ValueType
KOT_PCB_SHAPE: KiCadObjectType.ValueType
KOT_PCB_REFERENCE_IMAGE: KiCadObjectType.ValueType
KOT_PCB_FIELD: KiCadObjectType.ValueType
KOT_PCB_GENERATOR: KiCadObjectType.ValueType
KOT_PCB_TEXT: KiCadObjectType.ValueType
KOT_PCB_TEXTBOX: KiCadObjectType.ValueType
KOT_PCB_TABLE: KiCadObjectType.ValueType
KOT_PCB_TABLECELL: KiCadObjectType.ValueType
KOT_PCB_TRACE: KiCadObjectType.ValueType
KOT_PCB_VIA: KiCadObjectType.ValueType
KOT_PCB_ARC: KiCadObjectType.ValueType
KOT_PCB_MARKER: KiCadObjectType.ValueType
KOT_PCB_DIMENSION: KiCadObjectType.ValueType
KOT_PCB_ZONE: KiCadObjectType.ValueType
KOT_PCB_GROUP: KiCadObjectType.ValueType
KOT_SCH_MARKER: KiCadObjectType.ValueType
KOT_SCH_JUNCTION: KiCadObjectType.ValueType
KOT_SCH_NO_CONNECT: KiCadObjectType.ValueType
KOT_SCH_BUS_WIRE_ENTRY: KiCadObjectType.ValueType
KOT_SCH_BUS_BUS_ENTRY: KiCadObjectType.ValueType
KOT_SCH_LINE: KiCadObjectType.ValueType
KOT_SCH_SHAPE: KiCadObjectType.ValueType
KOT_SCH_BITMAP: KiCadObjectType.ValueType
KOT_SCH_TEXTBOX: KiCadObjectType.ValueType
KOT_SCH_TEXT: KiCadObjectType.ValueType
KOT_SCH_TABLE: KiCadObjectType.ValueType
KOT_SCH_TABLECELL: KiCadObjectType.ValueType
KOT_SCH_LABEL: KiCadObjectType.ValueType
KOT_SCH_GLOBAL_LABEL: KiCadObjectType.ValueType
KOT_SCH_HIER_LABEL: KiCadObjectType.ValueType
KOT_SCH_DIRECTIVE_LABEL: KiCadObjectType.ValueType
KOT_SCH_FIELD: KiCadObjectType.ValueType
KOT_SCH_SYMBOL: KiCadObjectType.ValueType
KOT_SCH_SHEET_PIN: KiCadObjectType.ValueType
KOT_SCH_SHEET: KiCadObjectType.ValueType
KOT_SCH_PIN: KiCadObjectType.ValueType
KOT_LIB_SYMBOL: KiCadObjectType.ValueType
' KOT_LIB_SHAPE = 40;\n KOT_LIB_TEXT = 41;\n KOT_LIB_TEXTBOX = 42;\n KOT_LIB_PIN = 43;\n KOT_LIB_FIELD = 44;\n'
KOT_WSG_LINE: KiCadObjectType.ValueType
KOT_WSG_RECT: KiCadObjectType.ValueType
KOT_WSG_POLY: KiCadObjectType.ValueType
KOT_WSG_TEXT: KiCadObjectType.ValueType
KOT_WSG_BITMAP: KiCadObjectType.ValueType
KOT_WSG_PAGE: KiCadObjectType.ValueType
KOT_SCH_GROUP: KiCadObjectType.ValueType
KOT_PCB_BARCODE: KiCadObjectType.ValueType
global___KiCadObjectType = KiCadObjectType

class _HorizontalAlignment:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HorizontalAlignmentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HorizontalAlignment.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HA_UNKNOWN: _HorizontalAlignment.ValueType
    HA_LEFT: _HorizontalAlignment.ValueType
    HA_CENTER: _HorizontalAlignment.ValueType
    HA_RIGHT: _HorizontalAlignment.ValueType
    HA_INDETERMINATE: _HorizontalAlignment.ValueType

class HorizontalAlignment(_HorizontalAlignment, metaclass=_HorizontalAlignmentEnumTypeWrapper):
    """Mapped to GR_TEXT_H_ALIGN_T"""
HA_UNKNOWN: HorizontalAlignment.ValueType
HA_LEFT: HorizontalAlignment.ValueType
HA_CENTER: HorizontalAlignment.ValueType
HA_RIGHT: HorizontalAlignment.ValueType
HA_INDETERMINATE: HorizontalAlignment.ValueType
global___HorizontalAlignment = HorizontalAlignment

class _VerticalAlignment:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VerticalAlignmentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VerticalAlignment.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VA_UNKNOWN: _VerticalAlignment.ValueType
    VA_TOP: _VerticalAlignment.ValueType
    VA_CENTER: _VerticalAlignment.ValueType
    VA_BOTTOM: _VerticalAlignment.ValueType
    VA_INDETERMINATE: _VerticalAlignment.ValueType

class VerticalAlignment(_VerticalAlignment, metaclass=_VerticalAlignmentEnumTypeWrapper):
    """Mapped to GR_TEXT_V_ALIGN_T"""
VA_UNKNOWN: VerticalAlignment.ValueType
VA_TOP: VerticalAlignment.ValueType
VA_CENTER: VerticalAlignment.ValueType
VA_BOTTOM: VerticalAlignment.ValueType
VA_INDETERMINATE: VerticalAlignment.ValueType
global___VerticalAlignment = VerticalAlignment

class _StrokeLineStyle:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StrokeLineStyleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StrokeLineStyle.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SLS_UNKNOWN: _StrokeLineStyle.ValueType
    SLS_DEFAULT: _StrokeLineStyle.ValueType
    SLS_SOLID: _StrokeLineStyle.ValueType
    SLS_DASH: _StrokeLineStyle.ValueType
    SLS_DOT: _StrokeLineStyle.ValueType
    SLS_DASHDOT: _StrokeLineStyle.ValueType
    SLS_DASHDOTDOT: _StrokeLineStyle.ValueType

class StrokeLineStyle(_StrokeLineStyle, metaclass=_StrokeLineStyleEnumTypeWrapper):
    """Mapped to LINE_STYLE"""
SLS_UNKNOWN: StrokeLineStyle.ValueType
SLS_DEFAULT: StrokeLineStyle.ValueType
SLS_SOLID: StrokeLineStyle.ValueType
SLS_DASH: StrokeLineStyle.ValueType
SLS_DOT: StrokeLineStyle.ValueType
SLS_DASHDOT: StrokeLineStyle.ValueType
SLS_DASHDOTDOT: StrokeLineStyle.ValueType
global___StrokeLineStyle = StrokeLineStyle