"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

generators.proto
Messages that describe content generators
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GeneratorParameterDataType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GeneratorParameterDataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GeneratorParameterDataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPDT_UNKNOWN: _GeneratorParameterDataType.ValueType
    GPDT_DISTANCE: _GeneratorParameterDataType.ValueType
    'int32 nanometers'
    GPDT_AREA: _GeneratorParameterDataType.ValueType
    'int32 square nanometers'
    GPDT_VOLUME: _GeneratorParameterDataType.ValueType
    'int32 cubic nanometers'
    GPDT_TIME: _GeneratorParameterDataType.ValueType
    'int32 picoseconds'
    GPDT_ANGLE: _GeneratorParameterDataType.ValueType
    'double degrees'
    GPDT_STRING: _GeneratorParameterDataType.ValueType
    GPDT_INTEGER: _GeneratorParameterDataType.ValueType
    'int32 (quantity, etc)'
    GPDT_REAL: _GeneratorParameterDataType.ValueType
    'double value'

class GeneratorParameterDataType(_GeneratorParameterDataType, metaclass=_GeneratorParameterDataTypeEnumTypeWrapper):
    ...
GPDT_UNKNOWN: GeneratorParameterDataType.ValueType
GPDT_DISTANCE: GeneratorParameterDataType.ValueType
'int32 nanometers'
GPDT_AREA: GeneratorParameterDataType.ValueType
'int32 square nanometers'
GPDT_VOLUME: GeneratorParameterDataType.ValueType
'int32 cubic nanometers'
GPDT_TIME: GeneratorParameterDataType.ValueType
'int32 picoseconds'
GPDT_ANGLE: GeneratorParameterDataType.ValueType
'double degrees'
GPDT_STRING: GeneratorParameterDataType.ValueType
GPDT_INTEGER: GeneratorParameterDataType.ValueType
'int32 (quantity, etc)'
GPDT_REAL: GeneratorParameterDataType.ValueType
'double value'
global___GeneratorParameterDataType = GeneratorParameterDataType

class _GeneratorParameterCategory:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GeneratorParameterCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GeneratorParameterCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPC_UNKNOWN: _GeneratorParameterCategory.ValueType
    GPC_PACKAGE: _GeneratorParameterCategory.ValueType
    GPC_PADS: _GeneratorParameterCategory.ValueType
    GPC_3DMODEL: _GeneratorParameterCategory.ValueType
    GPC_METADATA: _GeneratorParameterCategory.ValueType
    GPC_RULES: _GeneratorParameterCategory.ValueType

class GeneratorParameterCategory(_GeneratorParameterCategory, metaclass=_GeneratorParameterCategoryEnumTypeWrapper):
    ...
GPC_UNKNOWN: GeneratorParameterCategory.ValueType
GPC_PACKAGE: GeneratorParameterCategory.ValueType
GPC_PADS: GeneratorParameterCategory.ValueType
GPC_3DMODEL: GeneratorParameterCategory.ValueType
GPC_METADATA: GeneratorParameterCategory.ValueType
GPC_RULES: GeneratorParameterCategory.ValueType
global___GeneratorParameterCategory = GeneratorParameterCategory

class _GeneratedContentType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GeneratedContentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GeneratedContentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GCT_UNKNOWN: _GeneratedContentType.ValueType
    GCT_SYMBOL: _GeneratedContentType.ValueType
    GCT_FOOTPRINT: _GeneratedContentType.ValueType

class GeneratedContentType(_GeneratedContentType, metaclass=_GeneratedContentTypeEnumTypeWrapper):
    ...
GCT_UNKNOWN: GeneratedContentType.ValueType
GCT_SYMBOL: GeneratedContentType.ValueType
GCT_FOOTPRINT: GeneratedContentType.ValueType
global___GeneratedContentType = GeneratedContentType

@typing.final
class GeneratorParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    name: builtins.str
    description: builtins.str
    category: global___GeneratorParameterCategory.ValueType
    type: global___GeneratorParameterDataType.ValueType
    int_value: builtins.int
    double_value: builtins.float
    string_value: builtins.str

    def __init__(self, *, identifier: builtins.str=..., name: builtins.str=..., description: builtins.str=..., category: global___GeneratorParameterCategory.ValueType=..., type: global___GeneratorParameterDataType.ValueType=..., int_value: builtins.int=..., double_value: builtins.float=..., string_value: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['double_value', b'double_value', 'int_value', b'int_value', 'string_value', b'string_value', 'value', b'value']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['category', b'category', 'description', b'description', 'double_value', b'double_value', 'identifier', b'identifier', 'int_value', b'int_value', 'name', b'name', 'string_value', b'string_value', 'type', b'type', 'value', b'value']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['value', b'value']) -> typing.Literal['int_value', 'double_value', 'string_value'] | None:
        ...
global___GeneratorParameter = GeneratorParameter

@typing.final
class GeneratorInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    META_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int

    @property
    def meta(self) -> global___GeneratorMetaInfo:
        ...

    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeneratorParameter]:
        ...

    def __init__(self, *, meta: global___GeneratorMetaInfo | None=..., parameters: collections.abc.Iterable[global___GeneratorParameter] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['meta', b'meta']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['meta', b'meta', 'parameters', b'parameters']) -> None:
        ...
global___GeneratorInfo = GeneratorInfo

@typing.final
class GeneratorMetaInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPES_GENERATED_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    name: builtins.str
    description: builtins.str

    @property
    def types_generated(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___GeneratedContentType.ValueType]:
        ...

    def __init__(self, *, identifier: builtins.str=..., name: builtins.str=..., description: builtins.str=..., types_generated: collections.abc.Iterable[global___GeneratedContentType.ValueType] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['description', b'description', 'identifier', b'identifier', 'name', b'name', 'types_generated', b'types_generated']) -> None:
        ...
global___GeneratorMetaInfo = GeneratorMetaInfo