"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
from ... import common
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _JobStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JobStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JobStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    JS_UNSPECIFIED: _JobStatus.ValueType
    JS_SUCCESS: _JobStatus.ValueType
    JS_WARNING: _JobStatus.ValueType
    JS_ERROR: _JobStatus.ValueType

class JobStatus(_JobStatus, metaclass=_JobStatusEnumTypeWrapper):
    ...
JS_UNSPECIFIED: JobStatus.ValueType
JS_SUCCESS: JobStatus.ValueType
JS_WARNING: JobStatus.ValueType
JS_ERROR: JobStatus.ValueType
global___JobStatus = JobStatus

@typing.final
class RunJobResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    OUTPUT_PATH_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: global___JobStatus.ValueType
    message: builtins.str
    'Optional message containing warning or error details. Should be empty if status is JS_SUCCESS.'

    @property
    def output_path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The path of the generated output (may not actually exist in the filesystem if the job failed)
        May be a file, multiple files, or a directory depending on the context of the job
        """

    def __init__(self, *, status: global___JobStatus.ValueType=..., output_path: collections.abc.Iterable[builtins.str] | None=..., message: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['message', b'message', 'output_path', b'output_path', 'status', b'status']) -> None:
        ...
global___RunJobResponse = RunJobResponse

@typing.final
class RunJobSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCUMENT_FIELD_NUMBER: builtins.int
    OUTPUT_PATH_FIELD_NUMBER: builtins.int
    output_path: builtins.str
    "The path where the job's output should be saved\n    May be a file or a directory depending on the context of the job\n    "

    @property
    def document(self) -> common.types.base_types_pb2.DocumentSpecifier:
        """The document on which the job should be run"""

    def __init__(self, *, document: common.types.base_types_pb2.DocumentSpecifier | None=..., output_path: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['document', b'document']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['document', b'document', 'output_path', b'output_path']) -> None:
        ...
global___RunJobSettings = RunJobSettings