"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

wizards.proto
Messages that describe content generation wizards
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _WizardParameterDataType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WizardParameterDataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WizardParameterDataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WPDT_UNKNOWN: _WizardParameterDataType.ValueType
    WPDT_DISTANCE: _WizardParameterDataType.ValueType
    'int32 nanometers'
    WPDT_AREA: _WizardParameterDataType.ValueType
    'int32 square nanometers'
    WPDT_VOLUME: _WizardParameterDataType.ValueType
    'int32 cubic nanometers (not currently supported in KiCad)'
    WPDT_TIME: _WizardParameterDataType.ValueType
    'int32 picoseconds'
    WPDT_ANGLE: _WizardParameterDataType.ValueType
    'double degrees'
    WPDT_STRING: _WizardParameterDataType.ValueType
    WPDT_INTEGER: _WizardParameterDataType.ValueType
    'int32 (quantity, etc)'
    WPDT_REAL: _WizardParameterDataType.ValueType
    'double value'
    WPDT_BOOL: _WizardParameterDataType.ValueType
    'boolean flag'

class WizardParameterDataType(_WizardParameterDataType, metaclass=_WizardParameterDataTypeEnumTypeWrapper):
    ...
WPDT_UNKNOWN: WizardParameterDataType.ValueType
WPDT_DISTANCE: WizardParameterDataType.ValueType
'int32 nanometers'
WPDT_AREA: WizardParameterDataType.ValueType
'int32 square nanometers'
WPDT_VOLUME: WizardParameterDataType.ValueType
'int32 cubic nanometers (not currently supported in KiCad)'
WPDT_TIME: WizardParameterDataType.ValueType
'int32 picoseconds'
WPDT_ANGLE: WizardParameterDataType.ValueType
'double degrees'
WPDT_STRING: WizardParameterDataType.ValueType
WPDT_INTEGER: WizardParameterDataType.ValueType
'int32 (quantity, etc)'
WPDT_REAL: WizardParameterDataType.ValueType
'double value'
WPDT_BOOL: WizardParameterDataType.ValueType
'boolean flag'
global___WizardParameterDataType = WizardParameterDataType

class _WizardParameterCategory:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WizardParameterCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WizardParameterCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WPC_UNKNOWN: _WizardParameterCategory.ValueType
    WPC_PACKAGE: _WizardParameterCategory.ValueType
    WPC_PADS: _WizardParameterCategory.ValueType
    WPC_3DMODEL: _WizardParameterCategory.ValueType
    WPC_METADATA: _WizardParameterCategory.ValueType
    WPC_RULES: _WizardParameterCategory.ValueType

class WizardParameterCategory(_WizardParameterCategory, metaclass=_WizardParameterCategoryEnumTypeWrapper):
    ...
WPC_UNKNOWN: WizardParameterCategory.ValueType
WPC_PACKAGE: WizardParameterCategory.ValueType
WPC_PADS: WizardParameterCategory.ValueType
WPC_3DMODEL: WizardParameterCategory.ValueType
WPC_METADATA: WizardParameterCategory.ValueType
WPC_RULES: WizardParameterCategory.ValueType
global___WizardParameterCategory = WizardParameterCategory

class _WizardContentType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WizardContentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WizardContentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WCT_UNKNOWN: _WizardContentType.ValueType
    WCT_SYMBOL: _WizardContentType.ValueType
    WCT_FOOTPRINT: _WizardContentType.ValueType

class WizardContentType(_WizardContentType, metaclass=_WizardContentTypeEnumTypeWrapper):
    ...
WCT_UNKNOWN: WizardContentType.ValueType
WCT_SYMBOL: WizardContentType.ValueType
WCT_FOOTPRINT: WizardContentType.ValueType
global___WizardContentType = WizardContentType

class _WizardGenerationStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WizardGenerationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WizardGenerationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WGS_UNKNOWN: _WizardGenerationStatus.ValueType
    WGS_OK: _WizardGenerationStatus.ValueType
    WGS_ERROR: _WizardGenerationStatus.ValueType

class WizardGenerationStatus(_WizardGenerationStatus, metaclass=_WizardGenerationStatusEnumTypeWrapper):
    ...
WGS_UNKNOWN: WizardGenerationStatus.ValueType
WGS_OK: WizardGenerationStatus.ValueType
WGS_ERROR: WizardGenerationStatus.ValueType
global___WizardGenerationStatus = WizardGenerationStatus

@typing.final
class WizardIntParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    MULTIPLE_FIELD_NUMBER: builtins.int
    value: builtins.int
    default: builtins.int
    min: builtins.int
    max: builtins.int
    multiple: builtins.int
    'If present, will require the value to be a multiple of this number'

    def __init__(self, *, value: builtins.int=..., default: builtins.int=..., min: builtins.int | None=..., max: builtins.int | None=..., multiple: builtins.int | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_max', b'_max', '_min', b'_min', '_multiple', b'_multiple', 'max', b'max', 'min', b'min', 'multiple', b'multiple']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_max', b'_max', '_min', b'_min', '_multiple', b'_multiple', 'default', b'default', 'max', b'max', 'min', b'min', 'multiple', b'multiple', 'value', b'value']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_max', b'_max']) -> typing.Literal['max'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_min', b'_min']) -> typing.Literal['min'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_multiple', b'_multiple']) -> typing.Literal['multiple'] | None:
        ...
global___WizardIntParameter = WizardIntParameter

@typing.final
class WizardRealParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    value: builtins.float
    default: builtins.float
    min: builtins.float
    max: builtins.float

    def __init__(self, *, value: builtins.float=..., default: builtins.float=..., min: builtins.float | None=..., max: builtins.float | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_max', b'_max', '_min', b'_min', 'max', b'max', 'min', b'min']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_max', b'_max', '_min', b'_min', 'default', b'default', 'max', b'max', 'min', b'min', 'value', b'value']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_max', b'_max']) -> typing.Literal['max'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_min', b'_min']) -> typing.Literal['min'] | None:
        ...
global___WizardRealParameter = WizardRealParameter

@typing.final
class WizardBoolParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    value: builtins.bool
    default: builtins.bool

    def __init__(self, *, value: builtins.bool=..., default: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['default', b'default', 'value', b'value']) -> None:
        ...
global___WizardBoolParameter = WizardBoolParameter

@typing.final
class WizardStringParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    VALIDATION_REGEX_FIELD_NUMBER: builtins.int
    value: builtins.str
    default: builtins.str
    validation_regex: builtins.str

    def __init__(self, *, value: builtins.str=..., default: builtins.str=..., validation_regex: builtins.str | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_validation_regex', b'_validation_regex', 'validation_regex', b'validation_regex']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_validation_regex', b'_validation_regex', 'default', b'default', 'validation_regex', b'validation_regex', 'value', b'value']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_validation_regex', b'_validation_regex']) -> typing.Literal['validation_regex'] | None:
        ...
global___WizardStringParameter = WizardStringParameter

@typing.final
class WizardParameterList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARAMETERS_FIELD_NUMBER: builtins.int

    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WizardParameter]:
        ...

    def __init__(self, *, parameters: collections.abc.Iterable[global___WizardParameter] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['parameters', b'parameters']) -> None:
        ...
global___WizardParameterList = WizardParameterList

@typing.final
class WizardParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    INT_FIELD_NUMBER: builtins.int
    REAL_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    'An internal identifier for this parameter; must be unique within a wizard'
    name: builtins.str
    'The human-readable name for this parameter (may be translated)'
    description: builtins.str
    'A human-readable description / tooltip string (may be translated)'
    category: global___WizardParameterCategory.ValueType
    type: global___WizardParameterDataType.ValueType

    @property
    def int(self) -> global___WizardIntParameter:
        ...

    @property
    def real(self) -> global___WizardRealParameter:
        ...

    @property
    def bool(self) -> global___WizardBoolParameter:
        ...

    @property
    def string(self) -> global___WizardStringParameter:
        ...

    def __init__(self, *, identifier: builtins.str=..., name: builtins.str=..., description: builtins.str=..., category: global___WizardParameterCategory.ValueType=..., type: global___WizardParameterDataType.ValueType=..., int: global___WizardIntParameter | None=..., real: global___WizardRealParameter | None=..., bool: global___WizardBoolParameter | None=..., string: global___WizardStringParameter | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['bool', b'bool', 'int', b'int', 'real', b'real', 'string', b'string', 'value', b'value']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['bool', b'bool', 'category', b'category', 'description', b'description', 'identifier', b'identifier', 'int', b'int', 'name', b'name', 'real', b'real', 'string', b'string', 'type', b'type', 'value', b'value']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['value', b'value']) -> typing.Literal['int', 'real', 'bool', 'string'] | None:
        ...
global___WizardParameter = WizardParameter

@typing.final
class WizardInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    META_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int

    @property
    def meta(self) -> global___WizardMetaInfo:
        ...

    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WizardParameter]:
        ...

    def __init__(self, *, meta: global___WizardMetaInfo | None=..., parameters: collections.abc.Iterable[global___WizardParameter] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['meta', b'meta']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['meta', b'meta', 'parameters', b'parameters']) -> None:
        ...
global___WizardInfo = WizardInfo

@typing.final
class WizardMetaInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPES_GENERATED_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    name: builtins.str
    description: builtins.str

    @property
    def types_generated(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___WizardContentType.ValueType]:
        ...

    def __init__(self, *, identifier: builtins.str=..., name: builtins.str=..., description: builtins.str=..., types_generated: collections.abc.Iterable[global___WizardContentType.ValueType] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['description', b'description', 'identifier', b'identifier', 'name', b'name', 'types_generated', b'types_generated']) -> None:
        ...
global___WizardMetaInfo = WizardMetaInfo

@typing.final
class WizardGeneratedContent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    status: global___WizardGenerationStatus.ValueType
    error_message: builtins.str

    @property
    def content(self) -> google.protobuf.any_pb2.Any:
        ...

    def __init__(self, *, status: global___WizardGenerationStatus.ValueType=..., content: google.protobuf.any_pb2.Any | None=..., error_message: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['content', b'content']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['content', b'content', 'error_message', b'error_message', 'status', b'status']) -> None:
        ...
global___WizardGeneratedContent = WizardGeneratedContent